### ISSUE TITLE
Maze command no longer works

### ISSUE THREAD

**Issue by jalenluorion** [Jo3-L/yagpdb-cc#100]
It appears that the website linked to the maze command does not function anymore. Can you verify this and change (or remove if cannot be changed) the command?

**Comment by thewilloftheshadow** [comment]
Can reproduce. I receive a 502 error from Apache when I navigate to the website

**Comment by Jo3-L** [comment]
@Crenshaw1312 any thoughts on fixing this, or do you agree with having it deleted for the time being?

**Comment by Crenshaw1312** [comment]
I suggest removing it for now until I find a fix. The site itself is also behaving oddly.
![Screen Shot 2020-11-16 at 9 01 29 AM](https://user-images.githubusercontent.com/68561594/99283212-8d837d00-27e9-11eb-9238-400d1ca8fc96.png)

There may be an issue on their end, or if they updated it.
