### ISSUE TITLE
Standard Timezones

### ISSUE THREAD

**Issue by Satty9361** [Jo3-L/yagpdb-cc#17]
Use standard timezones for stuff like worldclock.cc.lua or other timezone based stuff. 
This automatically handles daylight saving. Its also a issue in one of my ccs so putting this here as a reminder.

**Comment by IBP-0** [comment]
I just had to alter the offsets in -time and -worldclock by hand when my friend from the UK complained. 😅

**Comment by Jo3-L** [comment]
Fixed in last few commits, thanks for the reminder
