### ISSUE TITLE
User which left the server is still in the db

### ISSUE THREAD

**Issue by GenryMg** [Jo3-L/yagpdb-cc#21]
For the AFK and Leveling systems, users who already left the server are still stored in the db (see the attachments). I guess this can be solved by a dbDel in the leave message. Might want to look into it...

<img width="592" alt="Screenshot 2020-04-22 at 11 46 34" src="https://user-images.githubusercontent.com/58843937/79938355-f5a9f480-848e-11ea-8415-5fcae49cd191.png">

<img width="508" alt="Screenshot 2020-04-22 at 11 44 56" src="https://user-images.githubusercontent.com/58843937/79938346-f2166d80-848e-11ea-8615-e0d366d36a3b.png">

**Comment by Jo3-L** [comment]
Removing for AFK sounds reasonable, however, for leveling, I'd think that if I left a server and rejoined I should keep my XP. What's your thoughts on this?

**Comment by GenryMg** [comment]
Yeah, would be pretty annoying if a user left then joined back with no xp...
