### ISSUE TITLE
editing all messages

### ISSUE THREAD

**Issue by Satty9361** [Jo3-L/yagpdb-cc#22]
edit.CC.lua should be able to edit complex messages as well.

**Comment by Jo3-L** [comment]
Would `-content` flag in addition to the SimpleEmbed flags already available suffice?

**Comment by Satty9361** [comment]
Yeah i think just a simple -content flag does the trick

**Comment by Satty9361** [comment]
This is now done as of - [link](https://github.com/Jo3-L/yagpdb-cc/commit/6d06b5ea20699974fd85c92227bbc040c2a13650) .
