### ISSUE TITLE
Partnership system through rep

### ISSUE THREAD

**Issue by Jo3-L** [Jo3-L/yagpdb-cc#25]
Commonly requested system, give rep to user when they partner with another server, detect with discord link regex.

**Comment by RickeyJLancaster** [comment]
Isn't it as simple as:
Trigger `(https:\/\/)?discord.(gg|com\/invite|io|me)\/.+`
`{{execAdmin "+" .User}}`

Is necessary a file on the repo for that?

**Comment by Jo3-L** [comment]
Yeah, I was thinking of some embed stuff originally but most people that have asked for this have requested different variations on it - I agree that this isn't the best place for it. Closing for now.
