### ISSUE TITLE
-role-rewards does not work as written

### ISSUE THREAD

**Issue by reticenti** [Jo3-L/yagpdb-cc#39]
Trying to implement this awesome leveling script, and the only part that doesn't work is the -rr command. Any insight into how we can get it to work? We run it and nothing happens. Logs are enabled but no output.

**Comment by Jo3-L** [comment]
Hi, this is a question better suited for the [YAGPDB Support Server](https://discord.gg/wmw5zWh). You can also DM me directly at `Joe_#6041`.

I have the system set up on my server & many other users use it, haven't heard of this issue so it's likely on your end - we can troubleshoot further using either of the two options provided. Closing for now.
