### ISSUE TITLE
meta: Change file extensions to .MD?

### ISSUE THREAD

**Issue by Jo3-L** [Jo3-L/yagpdb-cc#40]
See title.
## Pros
* Descriptions are easier to read (instead of a leading comment, we can have markdown)
* Eliminates any possible confusion that YAGPDB CC has any relation to Lua or other programming languages
* Can still have syntax highlighting in codeblocks

## Cons
* Harder to copy code on mobile

**Comment by MatiasMFM2001** [comment]
I've just forked the repo and updated my file extensions via a Bash script. I've probably did it wrong, but the code isn't showing correctly

Anyways, I think you could have two folders, one with `.lua` and the other with `.MD` files

**Comment by Jo3-L** [comment]
@MatiasMFM2001 the idea here is not to simply copy all the existing code and change the file extension, but to move information about the CC itself (currently put in the leading comment) into the Markdown file itself so it is easier to read. Then, we can have a `Code` section (or similar) in a codeblock. This way we would retain current syntax highlighting while improving experience for users.

Personally, I am not in favor of the idea of having both `.lua` and `.md` files, but I can see the appeal (users can view CCs through the markdown files, and copy through the `.lua` file which is the code only). In this case I would argue that the `.lua` extension is not even needed - instead, `cc.md` and `cc.source.txt`.

Thanks for the input!

**Comment by MatiasMFM2001** [comment]
Ohhh, I understood!
I like the idea of only Markdown, but I'm thinking if I can solve it would be harder to copy on mobile. Maybe some "hybrid syntax"  that both Markdown and YAGPDB would be confortable with

**Comment by MatiasMFM2001** [comment]
I tried in [my repo, with `animal.md` CC.](https://github.com/MatiasMFM2001/yagpdb-cc/blob/master/fun/animal.md) I know `{{/*` is visible, but that allows Mobile users to tap on "View raw" and copy entire code to YAG's webpage, without worrying about syntax issues between languages

**Comment by Jo3-L** [comment]
> In this case I would argue that the `.lua` extension is not even needed - instead, `cc.md` and `cc.source.txt`.
Any thoughts about this? Great idea with the `{{/*`, but I'm somewhat hesitant about doing that as it's visually distracting (at least to me) and looks to be a typo at first glance.

**Comment by MatiasMFM2001** [comment]
> Any thoughts about this?
I agree, you can open a `.txt` with any software so that will save headaches

> Great idea with the `{{/*`, but I'm somewhat hesitant about doing that as it's visually distracting (at least to me) and looks to be a typo at first glance.
I agree that is unsightly, but I think is the only way to maintain compatibility with both languages, without asking users to manually delete X lines after copying the code to YAG's editor

I will still try to hide that

**Comment by Jo3-L** [comment]
Closing in favor of #53, which is essentially this issue but more thought-out and with an implementation proposal.
