### ISSUE TITLE
Suggestion System Readme

### ISSUE THREAD

**Issue by ironbelly** [Jo3-L/yagpdb-cc#62]
A bit of a primer would be useful.. For example
{{$Suggestion_Channel:=}} - Is this the suggestion channel where suggestions are posted after being accepted or the one where suggestions are made?
{{$Logging_Channel:=}} - What is the purpose of this and what is outputted to this channel?
{{$Implemented_Channel:=}} - In the sample config this is unique, is there any issue with it being the same as say logging or approved?
{{$Approved_Channel:=}} - Same question as above
{{$Upvote:="upvote:524907425531428864"}} - Assuming this is the emote and id, is it necessary to have the emote name and then the id or would just the ID work?  Might be usefulto do a step by step on how to grab this info is it's not very well known how to grab emote IDs.  It should also be made clear that this doesn't work with standard discord emojis which are svg files like /assets/08c0a077780263f3df97613e58e71744.svg , when entering in 08c0a077780263f3df97613e58e71744 after upvote or thumbsup in this case you are unable to save the response at all due to an error message of "Response Too Long" Even though the response is not longer than 10k chars, something about these values messes it up.

> -Open the emoji panel and make sure you have the emoji you want to use.
> -Next, open up the Developer Console, using Ctrl-Shift-I,then Ctrl-Shift-C. Click on the emoj you want to use.
> Provided you have done that correctly, something blue will show in the console. Look for a long link looking similar to this: https://cdn.discordapp.com/emojis/587026903584735243.gif?v=1
> -If you only want the ID, copy the thing between the emojis/ and the extension. (In this case it is 587026903584735243)

{{$Downvote:="downvote:524907425032175638"}} - same as above

**Comment by ironbelly** [comment]
Another thing, you are missing sa archive from the readme as well as mentioning that approved posts cannot be deleted and should be archived instead

**Comment by Satty9361** [comment]
So the logging channel is for logs and it is where notifications related to the suggestion behavior go. It is possible to have different channels for approved and implemented suggestions so that it is easier to find the currently approved/implemented suggestions without having to go through a large number of denied/dupe suggestions.

The default behavior is if approved/implemented suggestions are separate, then the original authors do get a ping in the logging channel. However if the channels are same, posts are simply embeds with the ping. I will make the pinged version the default behavior then.

**Comment by Satty9361** [comment]
Also, to add to the above, i thought everyone using yag ccs knew how reactions work. Custom emojis are "emojiname:emojiid" while default emojis are their corresponding unicode characters. This is already mentioned in the documentation but maybe ill add a quick note.

**Comment by Satty9361** [comment]
README is updated!
