### ISSUE TITLE
Suggestion V2: CC doesn't execute when message contains "YAGPDB" or mentions bot

### ISSUE THREAD

**Issue by MatiasMFM2001** [Jo3-L/yagpdb-cc#81]
Hi! I think It's expected behavior due to RegEx trigger. With this original message I've found it:
> -suggest Respecto a los cumpleaños:
> 1) Que el YAGPDB envíe un mensaje a las `0:00` hora UTC
> 2) Que lo envíe a las 0:00 hora CdeCountry (o sea, `0:00 UTC +6`)
> 3) Que no envíe ningún mensaje, y solo se encargue del rol de CdeCumpleaños ~~(esto último pendiente)~~

But just `-suggest YAGPDB` or `-suggest @YAGPDB` is enough. I didn't test SuggestionV1, so maybe it doesn't have this bug

**Comment by Satty9361** [comment]
It should work fine. Send me an invite and i can take a look when i am free. You will find me on yag support server.

**Comment by MatiasMFM2001** [comment]
Nice, thanks!

**Comment by MatiasMFM2001** [comment]
**Update:** Nevermind, this was my fault. I had this CC active, which was interfering with Suggestion's CC. I didn't think that would happen...
![imagen](https://user-images.githubusercontent.com/46432351/95299166-9fb9e500-0853-11eb-8100-8ac481f84253.png)

Sorry for this issue, I'll close it
