### ISSUE TITLE
Suggestion system 

### ISSUE THREAD

**Issue by jalenluorion** [Jo3-L/yagpdb-cc#82]
When I use an admin command, it says not valid ID when I clearly copied the right ID. I did not change anything

**Comment by Satty9361** [comment]
Probably some issue with your setup. The code should work fine.

**Comment by Windyo** [comment]
taht' sbecause you're referencing the suggestion number and not the ID. ID is the discord ID of the message.

**Comment by EsenRurouni** [comment]
> taht' sbecause you're referencing the suggestion number and not the ID. ID is the discord ID of the message.

What Satty is saying is that the code itself is correct, and working. The issue is likely you are coping the wrong message ID or that the cofig values weren't properly inputted. And make sure you are using the full code.

**Comment by Windyo** [comment]
> > taht' sbecause you're referencing the suggestion number and not the ID. ID is the discord ID of the message.
> 
> What Satty is saying is that the code itself is correct, and working. The issue is likely you are coping the wrong message ID or that the cofig values weren't properly inputted. And make sure you are using the full code.

Yes we both agree - the OP is not a valid issue, and the user is probably referring to the subscription via its number and not its ID.
