### ISSUE TITLE
Just want help, Not issue

### ISSUE THREAD

**Issue by jalenluorion** [Jo3-L/yagpdb-cc#84]
In the slot machines, for all users, there is no balance. How do I add and manage balance?

**Comment by Jo3-L** [comment]
the slot machine cc can be thought of as an example for adding a slot machine to an already complete economy system. in other words, you cannot use it as-is, you have to basically add your own currency system on top of it. there is an open PR to add a ready-to-use currency system but I haven't had time to review it as I'm quite busy with school & my own bot atm.

if you don't mind, please ask further questions in the YAGPDB support server instead, more people are able to help you there and I check that more often.
