### ISSUE TITLE
In suggestion system v2, there is an error

### ISSUE THREAD

**Issue by jalenluorion** [Jo3-L/yagpdb-cc#89]
I did not change anything, I get this issue. Failed executing template: template: CC #31:43:5: executing "CC #31" at <addReactions $Upvote>: error calling addReactions: HTTP 404 Not Found, {"message": "Unknown Message", "code": 10008}. Issue appears to be in addReactions. Maybe yagpdb changed or deprecated something?

**Comment by EsenRurouni** [comment]
After countless times or trying to reproduce this error, I haven't been able to do it. My best guess is that the problem is either YAG does not have the perms or your configuration is wrong or partially wrong.

**Comment by Jo3-L** [comment]
This is probably a one-time error, if you encounter it again please reopen the issue. Closing for now.
